# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: askai_service.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'askai_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import askai_pb2 as askai__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x61skai_service.proto\x12\x12\x63om.tcl.xr.service\x1a\x0b\x61skai.proto2\xae\x01\n\x0c\x41skAiService\x12M\n\x04\x63hat\x12 .com.tcl.xr.message.AskAiRequest\x1a!.com.tcl.xr.message.AskAiResponse0\x01\x12O\n\x06search\x12!.com.tcl.xr.message.SearchRequest\x1a\".com.tcl.xr.message.SearchResponseB\x14\n\x12\x63om.tcl.xr.serviceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'askai_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\022com.tcl.xr.service'
  _globals['_ASKAISERVICE']._serialized_start=57
  _globals['_ASKAISERVICE']._serialized_end=231
# @@protoc_insertion_point(module_scope)
